//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReadmeDBEntities : DbContext
    {
        public ReadmeDBEntities()
            : base("name=ReadmeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comentario> comentarios { get; set; }
        public virtual DbSet<comunidad> comunidads { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<voto> votoes { get; set; }
    }
}
